---
- name: enable feature on all switches
  hosts: NXOS
  gather_facts: false
  connection: local
  vars:
    features:
      - { name: 'grpc', flag: 'enabled' }
      - { name: 'netconf', flag: 'enabled' }
      - { name: 'restconf', flag: 'enabled' }
      - { name: 'grpc', flag: 'enabled' }

  tasks:
    - name: enable features
      cisco.nxos.nxos_feature:
        feature: "{{ item.name }}"
        state: "{{ item.flag }}"
      loop: "{{ features }}"

    - name: check features
      cisco.nxos.nxos_command:
        commands:
          - command: show feature
        wait_for:
          - result[0] contains {{ item.name }}
      loop: "{{ features }}"
